# Generated by Django 5.1.6 on 2025-02-27 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cambiocontrasena',
            options={'verbose_name': 'Cambio de contraseña', 'verbose_name_plural': 'Cambios de contraseñas'},
        ),
        migrations.AlterModelOptions(
            name='intentosfallidos',
            options={'verbose_name': 'Intento Fallido', 'verbose_name_plural': 'Intentos Fallidos'},
        ),
        migrations.AlterModelOptions(
            name='sesiones',
            options={'verbose_name': 'Sesión', 'verbose_name_plural': 'Sesiones'},
        ),
    ]
