# Generated by Django 5.1.6 on 2025-03-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token_recuperacion',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
