# Generated by Django 5.1.6 on 2025-03-28 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('can_view_usuario_custom', 'Can view usuario custom'), ('can_change_usuario_status', 'Can change usuario status'), ('can_change_usuario_rol', 'Can change usuario rol'), ('can_archive_usuario', 'Can archive usuario')], 'verbose_name': 'Usuario del Sistema', 'verbose_name_plural': 'Usuarios del Sistema'},
        ),
    ]
