# Generated by Django 5.1.6 on 2025-04-20 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('can_access_user_administration', 'Can access user administration page'), ('can_view_usuario_custom', 'Can view usuario custom'), ('can_change_usuario_status', 'Can change usuario status'), ('can_change_usuario_rol', 'Can change usuario rol'), ('can_archive_usuario', 'Can archive usuario')], 'verbose_name': 'Usuario del Sistema', 'verbose_name_plural': 'Usuarios del Sistema'},
        ),
        migrations.CreateModel(
            name='UsuarioArchivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_archivado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Archivado')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo del Archivado')),
                ('archivado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_archivados_por_mi', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por')),
                ('usuario_archivado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_archivado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Archivado')),
            ],
            options={
                'verbose_name': 'Usuario Archivado',
                'verbose_name_plural': 'Usuarios Archivados',
                'db_table': 'usuarios_archivados',
                'db_table_comment': 'Registro de usuarios archivados, quién los archivó y por qué.',
                'ordering': ['-fecha_archivado'],
            },
        ),
    ]
