# Generated by Django 5.1.6 on 2025-06-06 18:21

import usuarios.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuario_options_usuarioarchivado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('puede_crear_empresa', 'Puede crear empresa'), ('puede_editar_empresa', 'Puede editar empresa'), ('puede_activar_desactivar_empresa', 'Puede activar/desactivar empresa'), ('puede_ver_empresa', 'Puede ver información de empresa'), ('puede_cambiar_rol_usuario', 'Puede cambiar el rol de usuario'), ('puede_activar_desactivar_usuario', 'Puede activar/desactivar usuario'), ('puede_archivar_usuario', 'Puede archivar usuario'), ('puede_editar_usuario', 'Puede editar usuario'), ('puede_crear_rol', 'Puede crear rol'), ('puede_editar_rol', 'Puede editar rol'), ('puede_eliminar_rol', 'Puede eliminar rol')], 'verbose_name': 'Usuario del Sistema', 'verbose_name_plural': 'Usuarios del Sistema'},
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', usuarios.models.UsuarioManager()),
            ],
        ),
    ]
