# Generated by Django 5.1.6 on 2025-02-27 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoria',
            options={'ordering': ['-fecha_accion'], 'verbose_name': 'Registro de Auditoría', 'verbose_name_plural': 'Registros de Auditorías'},
        ),
        migrations.AlterModelOptions(
            name='registroacciones',
            options={'verbose_name': 'Registro de Accion', 'verbose_name_plural': 'Registros de Acciones'},
        ),
    ]
