# Generated by Django 5.1.6 on 2025-03-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0003_alter_auditoria_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroacciones',
            options={'verbose_name': 'Registro de Acción', 'verbose_name_plural': 'Registros de Acciones'},
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='ip_usuario',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP del Usuario'),
        ),
        migrations.AlterField(
            model_name='registroacciones',
            name='fecha_accion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registroacciones',
            name='ip_usuario',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
