# Generated by Django 5.1.6 on 2025-03-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_alter_roles_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='nombre_rol',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
