# Generated by Django 5.1.6 on 2025-06-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('roles', '0003_alter_roles_nombre_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='permisos',
            field=models.ManyToManyField(blank=True, related_name='roles_asociados', to='auth.permission'),
        ),
    ]
