# Generated by Django 5.1.6 on 2025-04-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la Empresa')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('correo_corporativo', models.EmailField(max_length=254, verbose_name='Correo Electrónico Corporativo')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono Empresarial')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
            },
        ),
    ]
