# Generated by Django 5.1.6 on 2025-05-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_fecha_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
