# Generated by Django 5.2 on 2025-05-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado (Activo/Inactivo)'),
        ),
    ]
